<template>
  <main>
    <div class="page-header">
      <div class="container">
        <h1 class="">Sobre</h1>
      </div>
    </div>
    <div class="container">
      <div class="box">
        <p>Crud para gerenciamento de usuários</p>
        <p>Versão do sistema 1.0</p>
      </div>
    </div>
  </main>
</template>

<script>
  export default {
    name: 'sobre',
    data: () => ({
      
    })
  }
</script>
<style scoped>
</style>
